import { footerAct1, footerAct2, footerAct3 } from '../assets/base';
import {
  navSticker,
  databannercampaignBn1,
  databannercampaignBn1m,
  databannercampaignBn2,
  databannercampaignBn2m,
  databannercampaignBn3,
  databannercampaignBn3m,
  bannerDiscountPc,
  bannerDiscountMb,
  databannercardsAct1,
  databannercardsAct2,
  databannercardsAct3,
  databannercardsAct4,
  databannercardsAct5,
  databannerslidesBn1,
  databannerslidesBn2,
  bannerOnsaleTitle,
  databannercoupon1,
  databannercoupon2,
  databankBn1Pc,
  databankBn1Mb,
  databankBn2Pc,
  databankBn2Mb,
  databankBn3Pc,
  databankBn3Mb,
  datacategoryBn1,
  datacategoryBn2,
  datacategoryBn3,
  datacategoryBn4,
  datacategoryBn5,
  datacategoryBn6,
  datacategoryBn7,
  datacategoryBn8,
  datacategoryBn9,
  datacategoryBn10,
  datacategoryBn11,
  datacategoryBn12,
  datacategoryBn13,
  datacategoryBn14,
  datapreviewSlide11,
  datapreviewSlide12,
  datapreviewSlide21,
  datapreviewSlide22,
  placeImg,
  onsaleDaajcn1900JERMI,
  onsaleDaao4k1900I5MBQ,
  onsaleDbabgwA900C2JED,
  onsaleDbaehb1900I6JGX,
  onsaleDbat8bA83578799,
  onsaleDbbc1eA9007PF9Y,
  onsaleDbbj071900F2VXM,
  onsaleDbcrl8A900JFT6Y,
  onsaleDbcz4qA900JD56O,
  onsaleDcakhpA900HEQ4H,
  onsaleDcbf01A900IUNKQ,
  onsaleDeawn3A900J1ZT9,
  onsaleDebv7oA900IOXYG,
  onsaleDebwa9A900GC92D,
  onsaleDgadkxA900JB6K8,
  onsaleDhas87A900J03M8,
  onsaleDidi2wA900ANP7Y,
  onsaleDmadfeA900HLJTD,
  onsaleDmaxb4A900J3TQO,
  onsaleDmaz1gA900FSV0J,
  onsaleDmba2yA900FVOQD,
  onsaleDmbl1cA900JA04J,
  onsaleDmbq0oA900GYMML,
  onsaleDmbq0vA900IGNT1,
  onsaleDpae6z1900J5B9T,
  onsaleDqbe2m1900JDO0N,
  onsaleDqcbdeA900IT5FG,
  onsaleDradky1900J5DJ6,
  onsaleDsabajA900JEGIH,
  onsaleDsabkbA900ITEBX,
  onsaleDsabrhA900JDPCH,
  onsaleDsao8sA900IUHYW,
  onsaleDyafm9A900ISBWO,
  onsaleDyaq9d1900J2XSA,
  onsaleDyawdjA900JF93O,
  onsaleDyba0xA900JBRC1,
  databrandpdBn1,
  databrandpdBn2,
  databrandpdBn3,
  databrandpdBn4,
  databrandpdBn5,
  databrandsBn1,
  databrandsBn2,
  databrandsBn3,
  databrandsBn4,
  datapdgroupBn1,
  datapdgroupBn2,
} from '../assets/layout';

export const mockPdData = [
  {
    BlockId: 31,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '揪團pk',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercampaignBn1,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '揪團pk',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercampaignBn1m,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '天降紅包',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercampaignBn2,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '天降紅包',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercampaignBn2m,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '天天簽到',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercampaignBn3,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '天天簽到',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercampaignBn3m,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '最高回饋',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bannerDiscountPc,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: '最高回饋',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bannerDiscountMb,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 42,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '優惠活動',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercardsAct1,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 53,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '瘋殺',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bannerOnsaleTitle,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '優惠活動1',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercardsAct2,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '優惠活動2',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercardsAct3,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '優惠活動3',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercardsAct4,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '優惠活動4',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercardsAct5,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 64,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '超品日輪播',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannerslidesBn1,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '品類日輪播',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannerslidesBn2,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 220,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercoupon1,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '限時優惠',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databannercoupon2,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 231,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '銀行',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databankBn1Pc,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '銀行',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databankBn1Mb,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '銀行',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databankBn2Pc,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '銀行',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databankBn2Mb,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '銀行',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databankBn3Pc,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '銀行',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: databankBn3Mb,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 242,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '11/11限定',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datapreviewSlide11,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '11/12限定',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datapreviewSlide12,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '11/13限定',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datapreviewSlide21,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '11/14限定',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datapreviewSlide22,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 88,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '主機',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn1,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '3C週邊',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn2,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '大家電',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn5,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '小家電',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn6,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '數位',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn3,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '通訊',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn4,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '居家',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn7,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: '生活',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn8,
        imgTitle: '',
      },
      {
        id: 8,
        url: '',
        productName: '時尚',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn9,
        imgTitle: '',
      },
      {
        id: 9,
        url: '',
        productName: '戶外',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn10,
        imgTitle: '',
      },
      {
        id: 10,
        url: '',
        productName: '美妝',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn11,
        imgTitle: '',
      },
      {
        id: 11,
        url: '',
        productName: '日用',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn12,
        imgTitle: '',
      },
      {
        id: 12,
        url: '',
        productName: '食品',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn13,
        imgTitle: '',
      },
      {
        id: 13,
        url: '',
        productName: '保健',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datacategoryBn14,
        imgTitle: '',
      },
    ],
  },

  {
    BlockId: 99,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: 'Ergohuman 特仕版 2.0人體工學椅',
        productTitle: '登記送512P幣',
        marketPrice: '16500',
        discountPrice: '9999',
        imgSrc: onsaleDcakhpA900HEQ4H,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '雷蛇 Viper V3 PRO 毒蝰超輕量無線滑鼠',
        productTitle: '滿額送限量地墊',
        marketPrice: '4990',
        discountPrice: '3988',
        imgSrc: onsaleDcbf01A900IUNKQ,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: 'ACER X32 X2 OLED 32型 4K電競螢幕',
        productTitle: '領券限量再折1000',
        marketPrice: '26999',
        discountPrice: '18999',
        imgSrc: onsaleDsabajA900JEGIH,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: 'ASUS ROG Strix XG27UCG 27型 4K電競螢幕',
        productTitle: '限時搶券折1000',
        marketPrice: '14888',
        discountPrice: '8988',
        imgSrc: onsaleDsabkbA900ITEBX,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '石頭科技F25 Ultra吸拖洗地機',
        productTitle: '登記送1212P',
        marketPrice: '39900',
        discountPrice: '17912',
        imgSrc: onsaleDmaxb4A900J3TQO,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: 'SHOWHAN N54強磁真空吸附360度旋轉支架',
        productTitle: '三軸折疊快速收納',
        marketPrice: '590',
        discountPrice: '299',
        imgSrc: onsaleDyafm9A900ISBWO,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '善存男性綜合維他命120錠',
        productTitle: '下單送7-11咖啡券',
        marketPrice: '910',
        discountPrice: '773',
        imgSrc: onsaleDbbc1eA9007PF9Y,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: 'PHILIPS 耳罩式耳機+真無線藍牙耳機組',
        productTitle: '現省$2410',
        marketPrice: '4000',
        discountPrice: '1590',
        imgSrc: onsaleDyaq9d1900J2XSA,
        imgTitle: '',
      },
      {
        id: 8,
        url: '',
        productName: '海爾 17.5公升一級能效除濕機',
        productTitle: '貨物稅減免$1200',
        marketPrice: '7980',
        discountPrice: '5911',
        imgSrc: onsaleDmbq0vA900IGNT1,
        imgTitle: '',
      },
      {
        id: 9,
        url: '',
        productName: 'Glolux 延長線1.5M 2入組',
        productTitle: '限量破盤',
        marketPrice: '899',
        discountPrice: '599',
        imgSrc: onsaleDqbe2m1900JDO0N,
        imgTitle: '',
      },
      {
        id: 10,
        url: '',
        productName: '華碩 TUF Gaming RTX 5060 8GB OC 顯示卡',
        productTitle: '限時下殺$1000',
        marketPrice: '12990',
        discountPrice: '11990',
        imgSrc: onsaleDradky1900J5DJ6,
        imgTitle: '',
      },
      {
        id: 11,
        url: '',
        productName: '三花 吸汗透氣無痕肌紳士休閒襪6雙組',
        productTitle: '不易滑動 單雙99',
        marketPrice: '1680',
        discountPrice: '594',
        imgSrc: onsaleDidi2wA900ANP7Y,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 110,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: 'OVO K9 4K智慧投影機',
        productTitle: '加碼小方塊投影機',
        marketPrice: '36999',
        discountPrice: '32999',
        imgSrc: onsaleDpae6z1900J5B9T,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '象印不鏽鋼一體式杯蓋真空燜燒杯',
        productTitle: '12/6一日驚喜價',
        marketPrice: '2000',
        discountPrice: '888',
        imgSrc: onsaleDebwa9A900GC92D,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: 'MSI MPG 321URXW QD-OLED 32型 4K電競螢幕',
        productTitle: '限量登記送1212P',
        marketPrice: '27900',
        discountPrice: '21900',
        imgSrc: onsaleDsabrhA900JDPCH,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '飛利浦6開6座延長線1.8M',
        productTitle: '加碼送10%P',
        marketPrice: '799',
        discountPrice: '499',
        imgSrc: onsaleDsao8sA900IUHYW,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: 'POCO F8 Ultra 16GB/512GB',
        productTitle: '新機降千!抽P幣',
        marketPrice: '23999',
        discountPrice: '22999',
        imgSrc: onsaleDyawdjA900JF93O,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '石頭科技 Qrevo Curv 2 Flow 掃拖機器人',
        productTitle: '最高登記送2200P',
        marketPrice: '59999',
        discountPrice: '19999',
        imgSrc: onsaleDmbl1cA900JA04J,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '初品果高雄美濃雙色橙蜜小番茄禮盒3斤x2盒',
        productTitle: '初品果滿1212折80',
        marketPrice: '1400',
        discountPrice: '548',
        imgSrc: onsaleDbcz4qA900JD56O,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: '幫寶適 極上守護 一級幫 拉拉褲 4箱',
        productTitle: '下單最高送532P',
        marketPrice: '5196',
        discountPrice: '3999',
        imgSrc: onsaleDaao4k1900I5MBQ,
        imgTitle: '',
      },
      {
        id: 8,
        url: '',
        productName: 'Royal Canin 法國皇家室內成貓IN27 10KG',
        productTitle: '滿額登記送P幣',
        marketPrice: '3750',
        discountPrice: '2849',
        imgSrc: onsaleDebv7oA900IOXYG,
        imgTitle: '',
      },
      {
        id: 9,
        url: '',
        productName: '康寧 藍寶石鑄造不沾深炒鍋30cm(含蓋)',
        productTitle: '下單送100P',
        marketPrice: '2580',
        discountPrice: '999',
        imgSrc: onsaleDeawn3A900J1ZT9,
        imgTitle: '',
      },
      {
        id: 10,
        url: '',
        productName: 'Airwaves口香糖 超涼薄荷 28g*20入',
        productTitle: '贈30P幣+好禮',
        marketPrice: '676',
        discountPrice: '499',
        imgSrc: onsaleDbaehb1900I6JGX,
        imgTitle: '',
      },
      {
        id: 11,
        url: '',
        productName: 'Choetech 氮化鎵140W PD快充器-附240W線',
        productTitle: '充手機筆電 2年保',
        marketPrice: '3100',
        discountPrice: '999',
        imgSrc: onsaleDyba0xA900JBRC1,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 121,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '折疊款無段氣壓升降移動邊桌-2色可選',
        productTitle: '滿額登記送512P幣',
        marketPrice: '1999',
        discountPrice: '999',
        imgSrc: onsaleDqcbdeA900IT5FG,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '輝葉 震關健 2入組',
        productTitle: '下單贈1%P幣',
        marketPrice: '7960',
        discountPrice: '2612',
        imgSrc: onsaleDmadfeA900HLJTD,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: 'Casa 卡薩濾掛咖啡綜合組100入',
        productTitle: '下殺均入$6.5',
        marketPrice: '1380',
        discountPrice: '649',
        imgSrc: onsaleDbat8bA83578799,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: 'ASUS 16吋R9-RTX5060電競筆電',
        productTitle: '直接送1000P幣',
        marketPrice: '46999',
        discountPrice: '41599',
        imgSrc: onsaleDhas87A900J03M8,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: 'Red Bull 能量飲料 250ml (24罐/箱)',
        productTitle: '滿額登記送P幣',
        marketPrice: '1560',
        discountPrice: '1049',
        imgSrc: onsaleDbabgwA900C2JED,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: 'PENTAX 17 底片相機 TKO標準版',
        productTitle: '狂降$2000',
        marketPrice: '17800',
        discountPrice: '15800',
        imgSrc: onsaleDgadkxA900JB6K8,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '上山採藥台灣茶系列洗髮/沐浴-任選4入',
        productTitle: '下單贈護唇膏',
        marketPrice: '1196',
        discountPrice: '499',
        imgSrc: onsaleDaajcn1900JERMI,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: '克寧100%純生乳奶粉2.2kgx2罐',
        productTitle: '送雀巢焦糖瑪奇朵',
        marketPrice: '1740',
        discountPrice: '1212',
        imgSrc: onsaleDbbj071900F2VXM,
        imgTitle: '',
      },
      {
        id: 8,
        url: '',
        productName: '威技 6L抗菌除濕機',
        productTitle: '貨物稅減免$500',
        marketPrice: '6990',
        discountPrice: '2999',
        imgSrc: onsaleDmbq0oA900GYMML,
        imgTitle: '',
      },
      {
        id: 9,
        url: '',
        productName: '歐姆龍HBF-371體重體脂計銀色',
        productTitle: '下單贈100P幣',
        marketPrice: '4080',
        discountPrice: '2812',
        imgSrc: onsaleDmba2yA900FVOQD,
        imgTitle: '',
      },
      {
        id: 10,
        url: '',
        productName: '星巴克中杯雙果果汁星冰樂',
        productTitle: '即買即用全台通用',
        marketPrice: '125',
        discountPrice: '99',
        imgSrc: onsaleDbcrl8A900JFT6Y,
        imgTitle: '',
      },
      {
        id: 11,
        url: '',
        productName: '北方 陶瓷遙控電暖器',
        productTitle: '節能模式自動調溫',
        marketPrice: '3280',
        discountPrice: '2682',
        imgSrc: onsaleDmaz1gA900FSV0J,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 289,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: 'ACER X32 X2 OLED 32型 4K電競螢幕',
        productTitle: '領券限量再折1000',
        marketPrice: '26999',
        discountPrice: '18999',
        imgSrc: onsaleDsabajA900JEGIH,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: 'POCO F8 Ultra 16GB/512GB',
        productTitle: '新機降千!抽P幣',
        marketPrice: '23999',
        discountPrice: '22999',
        imgSrc: onsaleDyawdjA900JF93O,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '石頭科技F25 Ultra吸拖洗地機',
        productTitle: '登記送1212P',
        marketPrice: '39900',
        discountPrice: '17912',
        imgSrc: onsaleDmaxb4A900J3TQO,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: 'PENTAX 17 底片相機 TKO標準版',
        productTitle: '狂降$2000',
        marketPrice: '17800',
        discountPrice: '15800',
        imgSrc: onsaleDgadkxA900JB6K8,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '象印不鏽鋼一體式杯蓋真空燜燒杯',
        productTitle: '12/6一日驚喜價',
        marketPrice: '2000',
        discountPrice: '888',
        imgSrc: onsaleDebwa9A900GC92D,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: 'Choetech 氮化鎵140W PD快充器-附240W線',
        productTitle: '充手機筆電 2年保',
        marketPrice: '3100',
        discountPrice: '999',
        imgSrc: onsaleDyba0xA900JBRC1,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '星巴克中杯雙果果汁星冰樂',
        productTitle: '即買即用全台通用',
        marketPrice: '125',
        discountPrice: '99',
        imgSrc: onsaleDbcrl8A900JFT6Y,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: 'ASUS 16吋R9-RTX5060電競筆電',
        productTitle: '直接送1000P幣',
        marketPrice: '46999',
        discountPrice: '41599',
        imgSrc: onsaleDhas87A900J03M8,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 300,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: 'Ergohuman 特仕版 2.0人體工學椅',
        productTitle: '登記送512P幣',
        marketPrice: '16500',
        discountPrice: '9999',
        imgSrc: onsaleDcakhpA900HEQ4H,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: 'MSI MPG 321URXW QD-OLED 32型 4K電競螢幕',
        productTitle: '限量登記送1212P',
        marketPrice: '27900',
        discountPrice: '21900',
        imgSrc: onsaleDsabrhA900JDPCH,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '石頭科技 Qrevo Curv 2 Flow 掃拖機器人',
        productTitle: '最高登記送2200P',
        marketPrice: '59999',
        discountPrice: '19999',
        imgSrc: onsaleDmbl1cA900JA04J,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '初品果高雄美濃雙色橙蜜小番茄禮盒3斤x2盒',
        productTitle: '初品果滿1212折80',
        marketPrice: '1400',
        discountPrice: '548',
        imgSrc: onsaleDbcz4qA900JD56O,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '華碩 TUF Gaming RTX 5060 8GB OC 顯示卡',
        productTitle: '限時下殺$1000',
        marketPrice: '12990',
        discountPrice: '11990',
        imgSrc: onsaleDradky1900J5DJ6,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: 'Red Bull 能量飲料 250ml (24罐/箱)',
        productTitle: '滿額登記送P幣',
        marketPrice: '1560',
        discountPrice: '1049',
        imgSrc: onsaleDbabgwA900C2JED,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 311,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '膳魔師',
        productTitle: '獨家下殺65折',
        marketPrice: '16500',
        discountPrice: '9999',
        imgSrc: databrandsBn1,
        imgTitle: '膳魔師',
      },
      {
        id: 1,
        url: '',
        productName: 'Vero&Nique維諾妮卡',
        productTitle: '滿千送百限時優惠',
        marketPrice: '16500',
        discountPrice: '9999',
        imgSrc: databrandsBn2,
        imgTitle: 'Vero&Nique<br>維諾妮卡',
      },
      {
        id: 2,
        url: '',
        productName: '',
        productTitle: 'P幣加碼送',
        marketPrice: '16500',
        discountPrice: '9999',
        imgSrc: databrandsBn3,
        imgTitle: 'Vero&LE<br>CREUSET',
      },
      {
        id: 3,
        url: '',
        productName: 'MUJI 無印良品',
        productTitle: '衣料季節折扣4折起',
        marketPrice: '16500',
        discountPrice: '9999',
        imgSrc: databrandsBn4,
        imgTitle: 'MUJI 無印良品',
      },
    ],
  },
  {
    BlockId: 673,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '數位通訊狂慶',
        productTitle: '好禮加碼送 !',
        marketPrice: '16500',
        discountPrice: '9999',
        imgSrc: databrandpdBn1,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: 'Sony Xperia 1 V',
        productTitle: '滿2000登記抽',
        marketPrice: '40000',
        discountPrice: '38990 ',
        imgSrc: databrandpdBn2,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: 'SATUS T101 10吋 4G雙卡雙待平板',
        productTitle: '獨家下殺65折',
        marketPrice: '16500',
        discountPrice: '12990',
        imgSrc: databrandpdBn3,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: 'PlayStation PS4 NARUTO ',
        productTitle: '滿500送50P',
        marketPrice: '1900',
        discountPrice: '1590',
        imgSrc: databrandpdBn4,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: 'FUJIFILM 富士 instax mini 12',
        productTitle: '送拍立得束口袋',
        marketPrice: '2990',
        discountPrice: '2500',
        imgSrc: databrandpdBn5,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 684,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: 'ASUS ROG Strix XG27UCG 27型 4K電競螢幕',
        productTitle: '限時搶券折1000',
        marketPrice: '14888',
        discountPrice: '8988',
        imgSrc: onsaleDsabkbA900ITEBX,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: 'SHOWHAN N54強磁真空吸附360度旋轉支架',
        productTitle: '三軸折疊快速收納',
        marketPrice: '590',
        discountPrice: '299',
        imgSrc: onsaleDyafm9A900ISBWO,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: 'OVO K9 4K智慧投影機',
        productTitle: '加碼小方塊投影機',
        marketPrice: '36999',
        discountPrice: '32999',
        imgSrc: onsaleDpae6z1900J5B9T,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '幫寶適 極上守護 一級幫 拉拉褲 4箱',
        productTitle: '下單最高送532P',
        marketPrice: '5196',
        discountPrice: '3999',
        imgSrc: onsaleDaao4k1900I5MBQ,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '康寧 藍寶石鑄造不沾深炒鍋30cm(含蓋)',
        productTitle: '下單送100P',
        marketPrice: '2580',
        discountPrice: '999',
        imgSrc: onsaleDeawn3A900J1ZT9,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '輝葉 震關健 2入組',
        productTitle: '下單贈1%P幣',
        marketPrice: '7960',
        discountPrice: '2612',
        imgSrc: onsaleDmadfeA900HLJTD,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '上山採藥台灣茶系列洗髮/沐浴-任選4入',
        productTitle: '下單贈護唇膏',
        marketPrice: '1196',
        discountPrice: '499',
        imgSrc: onsaleDaajcn1900JERMI,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: '威技 6L抗菌除濕機',
        productTitle: '貨物稅減免$500',
        marketPrice: '6990',
        discountPrice: '2999',
        imgSrc: onsaleDmbq0oA900GYMML,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 695,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datapdgroupBn1,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: datapdgroupBn2,
        imgTitle: '',
      },
    ],
  },

  {
    BlockId: 816,
    Nodes: [
      {
        id: 1,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: footerAct1,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '揪團PK',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: footerAct2,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '激戰攻略',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: footerAct3,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 827,
    Nodes: [
      {
        id: 2,
        url: '',
        productName: '活動總覽',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: navSticker,
        imgTitle: '',
      },
    ],
  },
];
